name = "tick-tick-yt-sync"
main = "src/entry.py"
compatibility_date = "2025-12-01"
compatibility_flags = ["python_workers"]

[triggers]
crons = ["30 18 * * *"]

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]

[[kv_namespaces]]
binding = "YT_SYNC_KV"
id = "fa5b77c694fd4e2ba07b23e3e8f49cd7"